In [9]:
import numpy as np
from scipy import linalg as la

In [3]:
v = np.array([0.61, 0.93, 0.24, 0.27])
v.shape

(4,)

In [4]:
size = 3
zeros = np.zeros(shape=(3,))
zeros

array([0., 0., 0.])

In [5]:
size = 3
ones = np.ones(shape=(3,))
ones

array([1., 1., 1.])

In [6]:
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

a * b

array([-1, -4, 12])

In [7]:
np.inner(a, b)

7

In [8]:
np.dot(a, b)

7

In [10]:
a = np.array([2, 3])
la.norm(a)

3.605551275463989

In [11]:
np.abs(-1)

1

In [12]:
a = np.array([1, 3])
b = np.array([3, 1])

cos_theta_radian = np.dot(a, b) / (la.norm(a) * la.norm(b))

theta_radian = np.arccos(cos_theta_radian)

theta = theta_radian * 180 / np.pi

print('cos_theta_radian', cos_theta_radian)
print('theta_radian', theta_radian)
print('theta', theta)

cos_theta_radian 0.5999999999999999
theta_radian 0.9272952180016124
theta 53.130102354155994


In [13]:
a1 = np.array([0,0,1]).reshape(-1,1)
a1

array([[0],
       [0],
       [1]])

In [14]:
np.sqrt(2)

1.4142135623730951

In [16]:
A = np.array(np.random.RandomState(123).normal(size=16)).reshape(4, 4)
A.round(2)

array([[-1.09,  1.  ,  0.28, -1.51],
       [-0.58,  1.65, -2.43, -0.43],
       [ 1.27, -0.87, -0.68, -0.09],
       [ 1.49, -0.64, -0.44, -0.43]])