In [3]:
import numpy as np
import sympy
from scipy import linalg as la

In [4]:
A = np.arange(1, 10, 1).reshape(3, 3)

In [5]:
la.det(A)

0.0

In [6]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
A = np.array([[2, 1],
              [1, 2]])

In [8]:
eigenvalue, eigenvector = la.eig(A)

In [9]:
eigenvalue

array([3.+0.j, 1.+0.j])

In [10]:
eigenvector

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [11]:
eigenvector.round(2)

array([[ 0.71, -0.71],
       [ 0.71,  0.71]])

In [12]:
A = np.array([[9, -5, 1],
              [-5, 5, 3],
              [1, -3, 19]])

In [13]:
np.diag(A).sum()

33

In [14]:
w, v = la.eig(A)

In [15]:
np.sum(w)

(32.99999999999999+0j)

In [16]:
la.det(A)

456.00000000000006

In [17]:
np.prod(w)

(455.99999999999943+0j)