In [20]:
import numpy as np
from scipy import linalg as la

In [2]:
A = np.arange(1, 7).reshape(2,3)
B = np.arange(3, 9).reshape(2,3)

In [3]:
A + B

array([[ 4,  6,  8],
       [10, 12, 14]])

In [4]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
B = np.arange(3, 9).reshape(3,2)

In [7]:
A @ B

array([[34, 40],
       [79, 94]])

In [8]:
np.matmul(A, B)

array([[34, 40],
       [79, 94]])

In [9]:
A = np.arange(1, 13).reshape(4, 3)
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
A[[0, 2], :][:, [1, 2]]

array([[2, 3],
       [8, 9]])

In [11]:
np.identity(n=9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
np.identity(n=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.diag([3,6,9,12])

array([[ 3,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 12]])

In [14]:
np.triu(A)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [15]:
A = np.arange(1, 10).reshape(3,3)

In [18]:
np.triu(A, k =0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [19]:
np.tril(A)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [21]:
A = np.array([[1, 1],
              [1/2, -1]])
A

array([[ 1. ,  1. ],
       [ 0.5, -1. ]])

In [22]:
Q, R = la.qr(A)
Q = np.round(Q, 3)
R = np.round(R, 3)

In [23]:
Q

array([[-0.894, -0.447],
       [-0.447,  0.894]])

In [24]:
R

array([[-1.118, -0.447],
       [ 0.   , -1.342]])

In [25]:
A = np.random.RandomState(123).randint(1, 9, 9).reshape(3, 3)
A

array([[7, 6, 7],
       [3, 5, 3],
       [7, 2, 4]])

In [26]:
np.linalg.matrix_rank(A)

3

In [27]:
A_inv = la.inv(A)

In [28]:
A_inv

array([[-2.74509804e-01,  1.96078431e-01,  3.33333333e-01],
       [-1.76470588e-01,  4.11764706e-01,  5.55111512e-17],
       [ 5.68627451e-01, -5.49019608e-01, -3.33333333e-01]])